export const Data = [
  {
    name: "Collecting",
    category: "Collecting",
    title: "Collecting",
    value: Math.floor(10 * Math.random()),
    color: "#" + Math.floor(Math.random() * 16777215).toString(16),
  },
  {
    name: "Arts",
    category: "Arts",
    title: "Arts",
    value: Math.floor(10 * Math.random()),
    color: "#" + Math.floor(Math.random() * 16777215).toString(16),
  },
  {
    name: "Games",
    category: "Games",
    title: "Games",
    value: Math.floor(10 * Math.random()),
    color: "#" + Math.floor(Math.random() * 16777215).toString(16),
  },
  {
    name: "Model & Electronics",
    category: "Model & Electronics",
    title: "Model & Electronics",
    value: Math.floor(10 * Math.random()),
    color: "#" + Math.floor(Math.random() * 16777215).toString(16),
  },
  {
    name: "performing arts",
    category: "performing arts",
    title: "performing arts",
    value: Math.floor(10 * Math.random()),
    color: "#" + Math.floor(Math.random() * 16777215).toString(16),
  },
  {
    name: "sports/outdoor",
    category: "sports/outdoor",
    title: "sports/outdoor",
    value: Math.floor(10 * Math.random()),
    color: "#" + Math.floor(Math.random() * 16777215).toString(16),
  },
  {
    name: "music",
    category: "music",
    title: "music",
    value: Math.floor(10 * Math.random()),
    color: "#" + Math.floor(Math.random() * 16777215).toString(16),
  },
  {
    name: "spiritual & mental",
    category: "spiritual & mental",
    title: "spiritual & mental",
    value: Math.floor(10 * Math.random()),
    color: "#" + Math.floor(Math.random() * 16777215).toString(16),
  },
  {
    name: "food & drink",
    category: "food & drink",
    title: "food & drink",
    value: Math.floor(10 * Math.random()),
    color: "#" + Math.floor(Math.random() * 16777215).toString(16),
  },
  {
    name: "pets",
    category: "pets",
    title: "pets",
    value: Math.floor(10 * Math.random()),
    color: "#" + Math.floor(Math.random() * 16777215).toString(16),
  },
  {
    name: "work",
    category: "work",
    title: "work",
    value: Math.floor(10 * Math.random()),
    color: "#" + Math.floor(Math.random() * 16777215).toString(16),
  },
  {
    name: "Entertainment",
    category: "Entertainment",
    title: "Entertainment",
    value: Math.floor(10 * Math.random()),
    color: "#" + Math.floor(Math.random() * 16777215).toString(16),
  },
];
